### PR TITLE
deps: updates wazero to 1.0.0-pre.3

### PR DESCRIPTION
**Pull request by codefromthecrypt**
This updates [wazero](https://wazero.io/) to [1.0.0-pre.3](https://github.com/tetratelabs/wazero/releases/tag/v1.0.0-pre.3). This is the last release that will build with Go 1.17.

Notably, this improves performance and changes host function syntax.

### CODE REVIEW

**Comment by lthibault** [comment]
@codefromthecrypt Wow, thanks for this!  Much appreciated!

(P.S.:  I never responded to your [helpful comment](https://github.com/tetratelabs/wazero/issues/279#issuecomment-1278280844), but it hasn't gone unnoticed!  Thanks for that as well -- I'll reply once I find a bit of time to hack on this. 🙂)

**Comment by codefromthecrypt** [comment]
nice to hear from you again. catch you later!

**Review by lthibault — APPROVED** [review]

**Comment by codefromthecrypt** [comment]
@lthibault ps we're on gophers slack too, if you feel like chatting.

**Comment by lthibault** [comment]
@codefromthecrypt Thanks, as usual 🙂 

Re Slack, do you guys have a Matrix channel by any chance?  (I highly recommend it, if you don't have one already!)

**Comment by lthibault** [comment]
Tagging @mikelsr since this will impact your work.   Feel free to merge when you're happy with it.

**Pull request merged**
