### PR TITLE
nat config

### PR DESCRIPTION
**Pull request by aratz-lasa**
This PR add the libp2p NAT option to the Wetware server

### CODE REVIEW

**Comment by aratz-lasa** [comment]
@lthibault it would be nice to test this by connecting our two laptops from home. And if it works... merge!

**Comment by lthibault** [comment]
Funny, I was just looking at this too, and thinking the same thing.  Might be fun to include Mikel too!  Why don't we do this next Friday?

**Comment by lthibault** [comment]
BTW, I think this needs to be updated.  It appears to be based on an old version of `runtime`.

**Comment by lthibault** [comment]
Closing, since this ended up being tricker than expected, and has been de-prioritized.

**Pull request closed without merging**
